image: node:latest

cache:
  paths:
  - node_modules/

stages:
  - test
  - deploy

test:
  stage: test
  script: 
    - npm install
    - npm build
  tags: [shared]

deploy:
  stage: deploy
  script:
    - apt-get update -qq && apt-get install -y -qq sshpass
    - sshpass -V
    - export SSHPASS=$USER_PASS
    - script -qc "sshpass -e ssh -o StrictHostKeyChecking=no root@$HOST 'cd $PROJECT_PATH && ls && bash $PROJECT_PATH/script/autorun.sh'"
  only:
    - master
  tags: [shared]